name: Deploy Argo CD
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: self-hosted-k8s-runner
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Deploy Argo CD
      run: |
        kubectl create namespace argocd
        kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
    - name: Enable Insecure Mode
      run: |
        kubectl patch deployment argocd-server -n argocd --type='json' -p='[{"op": "add", "path": "/spec/template/spec/containers/0/args", "value": ["--insecure"]}]'
